"""Adds a key column to the event

Revision ID: 99f41abc314a
Revises: b668bbf2d11a
Create Date: 2021-05-31 20:56:17.130583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f41abc314a'
down_revision = 'b668bbf2d11a'
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('event', sa.Column('key',
                                     sa.String(length=6),
                                     nullable=True,
                                     unique=True,
                                     index=True))
    conn = op.get_bind()
    conn.execute("update event set key=cast(id as varchar(6)) where key is null")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'key')
    # ### end Alembic commands ###
